behaviors:
  Sample:
    trainer_type: ppo
    behavioral_cloning:
      demo_path: /home/kai-yamashita/Desktop/AWSIM/Assets/Demonstrations/EgoVehicleDemo.demo
      strength: 1.0
      steps: 1000000
    reward_signals:
      gail:
        demonstration_path: /home/kai-yamashita/Desktop/AWSIM/Assets/Demonstrations/EgoVehicleDemo.demo
        strength: 0.1
        gamma: 0.99
        encoding_size: 64
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 10000
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
